#  Use official Node.js image as base
FROM node:20.11.0

# Set working directory within the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package.json .
COPY package-lock.json .

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Expose port 3000
EXPOSE 3000

# Run the Next.js application
CMD ["npm", "start"]
