import { SpeedInsights } from '@vercel/speed-insights/next';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { ThemeProvider } from "@/components/ThemeProvider";
import ClientProviders from "@/components/ClientProviders";
import FirebaseAuthProvider from "@/components/FirebaseAuthProvider";
import SubscriptionProvider from "@/components/SubscriptionProvider";
import { Toaster } from "@/components/ui/toaster";
import ScrollToTop from "react-scroll-to-top";
import Head from 'next/head';



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Glocal.ai",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <ClientProviders>
    <html lang="en">
      
      <body className="flex flex-col min-h-screen">
        <FirebaseAuthProvider>
          <SubscriptionProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
              >
             
             
             <script src="https://cdn.botpress.cloud/webchat/v1/inject.js" defer></script>
        <script src="https://mediafiles.botpress.cloud/cd1f11a5-5d03-4cc0-8057-c1bbddb7437e/webchat/config.js" defer></script>
              
              <Header /> 
              {/* <Smallscreenheader /> */}
            
              {children}
               {/* <Footer /> */}
              
              <Toaster />
            </ThemeProvider>
          </SubscriptionProvider>
        </FirebaseAuthProvider>
      </body>
    </html>
    </ClientProviders> 
  );
}










// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import Header from "@/components/Header";
// import Footer from "@/components/Footer";
// import { ThemeProvider } from "@/components/ThemeProvider";
// import ClientProviders from "@/components/ClientProviders";
// import FirebaseAuthProvider from "@/components/FirebaseAuthProvider";
// import SubscriptionProvider from "@/components/SubscriptionProvider";
// import { Toaster } from "@/components/ui/toaster";
// import ScrollToTop from "react-scroll-to-top";
// import Smallscreenheader from '@/components/Smallscreenheader'

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {

//   return (
//     <ClientProviders>
//     <html lang="en">
//       <body className="flex flex-col min-h-screen">
//         <FirebaseAuthProvider>
//           <SubscriptionProvider>
//             <ThemeProvider
//               attribute="class"
//               defaultTheme="system"
//               enableSystem
//               disableTransitionOnChange
//               >
//               <Header /> 
            

//               {children}

//                {/* <Footer /> */}
              
//               <Toaster />
//             </ThemeProvider>
//           </SubscriptionProvider>
//         </FirebaseAuthProvider>
//       </body>
//     </html>
//     </ClientProviders> 
//   );
// }
