name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # Add the setup-node action here to ensure correct Node.js version
      - uses: actions/setup-node@v3
        with:
          node-version: 18.17.0  # Adjust the version if needed (>= 18.17.0 for Next.js)

      - name: Install dependencies (adjust for your package manager)
        run: npm install  # Or yarn install if you use yarn

      # Your build and deploy steps here (replace with your specific commands)
      - name: Build Next.js app
        run: next build

      - name: Deploy to Azure Static Web Apps (replace with your deployment commands)
        # ... your deployment steps ...

  close_pull_request_job:  # Consider removing this job if not needed
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_BUSH_0EE88AB00 }}
          action: "close"
